# Generated by Django 3.0.3 on 2020-05-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_auto_20200516_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
